using System.Collections;
using UnityEngine;

public class SpaceTravelManager : MonoBehaviour
{
    [Header("Planets Hierarchy")]
    public GameObject[] proceduralPlanets; // The 4 empty parents generated by Giovanni

    [Header("Travel Animation Points")]
    public Transform spawnPointFar;        // Empty GameObject deep in outer space
    public Transform destinationPointClose; // Empty GameObject framed beautifully in our ship window
    public float travelDuration = 6f;       // Cozy, relaxing duration for the flight effect
    public AnimationCurve travelEaseCurve = AnimationCurve.EaseInOut(0, 0, 1, 1);

    private void Start()
    {
        // At the start of the game, I make sure all celestial bodies are hidden out of view
        foreach (GameObject planet in proceduralPlanets)
        {
            if (planet != null) planet.SetActive(false);
        }
    }

    public void StartTravelAnimation(int planetIndex)
    {
        if (planetIndex >= 0 && planetIndex < proceduralPlanets.Length)
        {
            StopAllCoroutines();
            StartCoroutine(AnimateSpaceFlight(planetIndex));
        }
    }

    private IEnumerator AnimateSpaceFlight(int index)
    {
        // I disable any previously active planet to ensure only our new destination exists
        foreach (GameObject planet in proceduralPlanets)
        {
            if (planet != null) planet.SetActive(false);
        }

        GameObject selectedPlanet = proceduralPlanets[index];

        if (selectedPlanet != null)
        {
            // I snap the selected planet to the faraway spawn point and turn its visibility ON
            selectedPlanet.transform.position = spawnPointFar.position;
            selectedPlanet.transform.rotation = spawnPointFar.rotation;
            selectedPlanet.SetActive(true);

            float elapsedTime = 0f;

            // I smoothly slide the miniature planet towards our ship window to mimic movement
            while (elapsedTime < travelDuration)
            {
                elapsedTime += Time.deltaTime;
                float normalizedTime = elapsedTime / travelDuration;

                // I use an evaluation curve to give it acceleration and deceleration feel
                float curveValue = travelEaseCurve.Evaluate(normalizedTime);

                selectedPlanet.transform.position = Vector3.Lerp(spawnPointFar.position, destinationPointClose.position, curveValue);

                // I apply a very subtle gentle rotation to the planet so it feels alive during flight
                selectedPlanet.transform.Rotate(Vector3.up * Time.deltaTime * 2f, Space.World);

                yield return null;
            }

            // I guarantee it sits exactly at the close destination coordinates when the loop finishes
            selectedPlanet.transform.position = destinationPointClose.position;

            // Log message to notify that we arrived safely at our destination scene context
            Debug.Log("Arrival animation completed. The ship is now orbiting the planet.");
        }
    }
}